spring:
  rabbitmq:
    host: 192.168.10.50
    port: 5672
    username: feeyeapp
    password: feeye2018
    publisher-confirms: true  #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true
server:
  port: 8081
